<?php

namespace App\Enums;

enum ErrorType: string
{
    case CODE_ACCOUNT_CANNOT_BE_REGISTERED = 'CODE_ACCOUNT_CANNOT_BE_REGISTERED';
    case STATUS_ACCOUNT_CANNOT_BE_REGISTERED = 'STATUS_ACCOUNT_CANNOT_BE_REGISTERED';
    case CODE_INVALID_TOKEN = 'CODE_INVALID_TOKEN';
    case STATUS_INVALID_TOKEN = 'STATUS_INVALID_TOKEN';
}
