name: Laravel tests on PR

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'laravel-api/**'
      - '.github/workflows/laravel-test.yml'

jobs:
  php-tests:
    if: ${{ github.event.pull_request.draft == false && !startsWith(github.head_ref, 'branch_') }}
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: lexis-test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: lexis-test
      DB_USERNAME: root
      DB_PASSWORD: secret

    defaults:
      run:
        working-directory: laravel-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql, mysql, mbstring, dom, fileinfo
          coverage: none
          tools: composer:v2

      - name: Validate composer files
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Generate APP_KEY
        run: echo APP_KEY=$(php -r 'echo "base64:".base64_encode(random_bytes(32));') >> $GITHUB_ENV

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h127.0.0.1 -P3306 -uroot -psecret --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Initialize database schema
        run: php artisan migrate:fresh --force

      - name: Clear config cache
        run: php artisan config:clear

      - name: Seed master data
        run: php artisan db:seed --force -n

      - name: Run tests
        run: php artisan test --colors=never
